version: "3.3"

services:
  laravel-app-1:
    build:
      context: ./docker/app/
      dockerfile: Dockerfile
    container_name: laravel-app-1
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./app1:/var/www
    networks:
      - docker-network

  laravel-prod-1:
    image: nginx:alpine
    container_name: laravel-prod-1
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./app1:/var/www
      - ./docker/nginx/nginx-app1.conf:/etc/nginx/nginx.conf
    networks:
      - docker-network

  database:
    image: mysql:5.7
    container_name: database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "docker-rendu"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - docker-network

volumes:
  db-data:

networks:
  docker-network:
    driver: bridge
